name: Owasp Summit 2018
markdown: kramdown
data_dir: website/_data
includes_dir: website/_includes
layouts_dir:  website/_layouts
#gems:
#  - jekyll-feed
exclude:
  - CNAME
  - LICENSE
  - node_modules
  - gulpfile.coffee
  - gulpfile.js
  - wallaby.js
  - start.sh
  - package.json
  - params.json
  - README.md
  - Budget
  - Logistics/Design
  - Logistics/emails
  - Logistics/meetings
  - Logistics/archive
  - src
  - website/_temp_files

  - _pages/for-editors
  - _pages/schedule
  - _Participants
  - _Working-Sessions

